[{"id":578178850,"node_id":"R_kgDOInZPIg","name":"CVE-2019-9053-Python3","full_name":"pedrojosenavasperez/CVE-2019-9053-Python3","private":false,"owner":{"login":"pedrojosenavasperez","id":115498883,"node_id":"U_kgDOBuJfgw","avatar_url":"https://avatars.githubusercontent.com/u/115498883?v=4","url":"https://api.github.com/users/pedrojosenavasperez","html_url":"https://github.com/pedrojosenavasperez","type":"User","site_admin":false},"html_url":"https://github.com/pedrojosenavasperez/CVE-2019-9053-Python3","description":"CVE-2019-9053 exploit ported to python3","fork":false,"url":"https://api.github.com/repos/pedrojosenavasperez/CVE-2019-9053-Python3","created_at":"2022-12-14T12:50:54Z","updated_at":"2022-12-14T12:56:13Z","pushed_at":"2022-12-14T13:05:03Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1}]