[{"id":507639325,"node_id":"R_kgDOHkH2HQ","name":"CVE-2021-38314","full_name":"c0ff33b34n/CVE-2021-38314","private":false,"owner":{"login":"c0ff33b34n","id":86168298,"node_id":"MDQ6VXNlcjg2MTY4Mjk4","avatar_url":"https://avatars.githubusercontent.com/u/86168298?v=4","url":"https://api.github.com/users/c0ff33b34n","html_url":"https://github.com/c0ff33b34n","type":"User","site_admin":false},"html_url":"https://github.com/c0ff33b34n/CVE-2021-38314","description":"Python exploit for CVE-2021-38314","fork":false,"url":"https://api.github.com/repos/c0ff33b34n/CVE-2021-38314","created_at":"2022-06-26T17:23:40Z","updated_at":"2022-06-26T17:24:04Z","pushed_at":"2022-06-26T17:27:09Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1}]